[tool.poetry]
name = "portfolioctopt"
version = "0.1.0"
description = ""
authors = ["ggelabert <ggelabert@serikat.es>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
