[tool.poetry]
name = "portfolioctopt"
version = "0.1.0"
description = ""
authors = ["ggelabert <ggelabert@serikat.es>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.24.0"
dwave-ocean-sdk = "^6.1.1"
pandas = "^1.5.2"
openpyxl = "^3.0.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
